<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="activitydiagramTrace" nsURI="activitydiagramTrace" nsPrefix="activitydiagramTrace">
  <eClassifiers xsi:type="ecore:EClass" name="SpecificTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activitydiagram_ActivityNode_AddToken_Sequence" upperBound="-1" eType="//Steps/Activitydiagram_ActivityNode_AddToken"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activitydiagram_ActivityNode_Execute_Sequence" upperBound="-1" eType="//Steps/Activitydiagram_ActivityNode_Execute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activitydiagram_ActivityNode_RemoveToken_Sequence" upperBound="-1" eType="//Steps/Activitydiagram_ActivityNode_RemoveToken"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activitydiagram_ActivityNode_Terminate_Sequence" upperBound="-1" eType="//Steps/Activitydiagram_ActivityNode_Terminate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activitydiagram_Activity_Execute_Sequence" upperBound="-1" eType="//Steps/Activitydiagram_Activity_Execute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activitydiagram_BooleanVariable_Init_Sequence" upperBound="-1" eType="//Steps/Activitydiagram_BooleanVariable_Init"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activitydiagram_IntegerVariable_Init_Sequence" upperBound="-1" eType="//Steps/Activitydiagram_IntegerVariable_Init"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activitydiagram_Variable_Init_Sequence" upperBound="-1" eType="//Steps/Activitydiagram_Variable_Init"/>
    <eGenericSuperTypes>
      <eTypeArguments>
        <eTypeArguments>
          <eUpperBound eClassifier="//Steps/SpecificStep"/>
        </eTypeArguments>
        <eTypeArguments>
          <eUpperBound eClassifier="//States/SpecificState"/>
        </eTypeArguments>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SequentialStep"/>
      </eTypeArguments>
      <eTypeArguments eClassifier="//States/SpecificTracedObject">
        <eTypeArguments>
          <eUpperBound eClassifier="//States/SpecificDimension">
            <eTypeArguments>
              <eUpperBound eClassifier="//States/SpecificValue"/>
            </eTypeArguments>
          </eUpperBound>
        </eTypeArguments>
      </eTypeArguments>
      <eTypeArguments eClassifier="//States/SpecificState"/>
      <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//Trace"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eSubpackages name="Steps" nsURI="activitydiagramTrace_Steps" nsPrefix="events">
    <eClassifiers xsi:type="ecore:EClass" name="Activitydiagram_ActivityNode_AddToken">
      <eOperations name="getCaller" lowerBound="1" eType="//States/activitydiagram/TracedActivityNode">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (activitydiagramTrace.States.activitydiagram.TracedActivityNode) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
      </eOperations>
      <eGenericSuperTypes eClassifier="//Steps/SpecificStep"/>
      <eGenericSuperTypes>
        <eTypeArguments eClassifier="//States/SpecificState"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      </eGenericSuperTypes>
      <eGenericSuperTypes eClassifier="//Steps/Activitydiagram_Activity_Execute_AbstractSubStep"/>
      <eGenericSuperTypes eClassifier="//Steps/Activitydiagram_ActivityNode_Execute_AbstractSubStep"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Activitydiagram_ActivityNode_Execute">
      <eOperations name="getCaller" lowerBound="1" eType="//States/activitydiagram/TracedActivityNode">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (activitydiagramTrace.States.activitydiagram.TracedActivityNode) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
      </eOperations>
      <eGenericSuperTypes eClassifier="//Steps/Activitydiagram_Activity_Execute_AbstractSubStep"/>
      <eGenericSuperTypes eClassifier="//Steps/SpecificStep"/>
      <eGenericSuperTypes>
        <eTypeArguments eClassifier="//Steps/Activitydiagram_ActivityNode_Execute_AbstractSubStep"/>
        <eTypeArguments eClassifier="//States/SpecificState"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SequentialStep"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Activitydiagram_ActivityNode_Execute_AbstractSubStep" abstract="true" interface="true" eSuperTypes="//Steps/SpecificStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Activitydiagram_ActivityNode_Execute_ImplicitStep">
      <eGenericSuperTypes eClassifier="//Steps/Activitydiagram_ActivityNode_Execute_AbstractSubStep"/>
      <eGenericSuperTypes>
        <eTypeArguments eClassifier="//States/SpecificState"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Activitydiagram_ActivityNode_RemoveToken">
      <eOperations name="getCaller" lowerBound="1" eType="//States/activitydiagram/TracedActivityNode">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (activitydiagramTrace.States.activitydiagram.TracedActivityNode) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
      </eOperations>
      <eGenericSuperTypes eClassifier="//Steps/SpecificStep"/>
      <eGenericSuperTypes>
        <eTypeArguments eClassifier="//States/SpecificState"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Activitydiagram_ActivityNode_Terminate">
      <eOperations name="getCaller" lowerBound="1" eType="//States/activitydiagram/TracedActivityNode">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (activitydiagramTrace.States.activitydiagram.TracedActivityNode) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
      </eOperations>
      <eGenericSuperTypes eClassifier="//Steps/SpecificStep"/>
      <eGenericSuperTypes>
        <eTypeArguments eClassifier="//States/SpecificState"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Activitydiagram_Activity_Execute">
      <eOperations name="getCaller" lowerBound="1" eType="//States/activitydiagram/TracedActivity">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (activitydiagramTrace.States.activitydiagram.TracedActivity) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
      </eOperations>
      <eGenericSuperTypes eClassifier="//Steps/SpecificStep"/>
      <eGenericSuperTypes>
        <eTypeArguments eClassifier="//Steps/Activitydiagram_Activity_Execute_AbstractSubStep"/>
        <eTypeArguments eClassifier="//States/SpecificState"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SequentialStep"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Activitydiagram_Activity_Execute_AbstractSubStep" abstract="true" interface="true" eSuperTypes="//Steps/SpecificStep"/>
    <eClassifiers xsi:type="ecore:EClass" name="Activitydiagram_Activity_Execute_ImplicitStep">
      <eGenericSuperTypes eClassifier="//Steps/Activitydiagram_Activity_Execute_AbstractSubStep"/>
      <eGenericSuperTypes>
        <eTypeArguments eClassifier="//States/SpecificState"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Activitydiagram_BooleanVariable_Init">
      <eOperations name="getCaller" lowerBound="1" eType="//States/activitydiagram/TracedBooleanVariable">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (activitydiagramTrace.States.activitydiagram.TracedBooleanVariable) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
      </eOperations>
      <eGenericSuperTypes eClassifier="//Steps/Activitydiagram_Activity_Execute_AbstractSubStep"/>
      <eGenericSuperTypes eClassifier="//Steps/SpecificStep"/>
      <eGenericSuperTypes>
        <eTypeArguments eClassifier="//States/SpecificState"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Activitydiagram_IntegerVariable_Init">
      <eOperations name="getCaller" lowerBound="1" eType="//States/activitydiagram/TracedIntegerVariable">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (activitydiagramTrace.States.activitydiagram.TracedIntegerVariable) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
      </eOperations>
      <eGenericSuperTypes eClassifier="//Steps/Activitydiagram_Activity_Execute_AbstractSubStep"/>
      <eGenericSuperTypes eClassifier="//Steps/SpecificStep"/>
      <eGenericSuperTypes>
        <eTypeArguments eClassifier="//States/SpecificState"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Activitydiagram_Variable_Init">
      <eOperations name="getCaller" lowerBound="1" eType="//States/activitydiagram/TracedVariable">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="return (activitydiagramTrace.States.activitydiagram.TracedVariable) this.getMseoccurrence().getMse().getCaller();"/>
        </eAnnotations>
      </eOperations>
      <eGenericSuperTypes eClassifier="//Steps/Activitydiagram_Activity_Execute_AbstractSubStep"/>
      <eGenericSuperTypes eClassifier="//Steps/SpecificStep"/>
      <eGenericSuperTypes>
        <eTypeArguments eClassifier="//States/SpecificState"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RootImplicitStep">
      <eGenericSuperTypes>
        <eTypeArguments eClassifier="//States/SpecificState"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SpecificRootStep">
      <eGenericSuperTypes>
        <eTypeArguments eClassifier="//Steps/SpecificStep"/>
        <eTypeArguments eClassifier="//States/SpecificState"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SequentialStep"/>
      </eGenericSuperTypes>
      <eGenericSuperTypes eClassifier="//Steps/SpecificStep"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SpecificStep" abstract="true">
      <eGenericSuperTypes>
        <eTypeArguments eClassifier="//States/SpecificState"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//Step"/>
      </eGenericSuperTypes>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="States" nsURI="activitydiagramTrace_States" nsPrefix="tracedclasses">
    <eClassifiers xsi:type="ecore:EClass" name="ActivityEdge_offeredTokens_Dimension">
      <eGenericSuperTypes eClassifier="//States/SpecificDimension">
        <eTypeArguments eClassifier="//States/ActivityEdge_offeredTokens_Value"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActivityEdge_offeredTokens_Value">
      <eAnnotations source="http://www.modelexecution.org/trace/XMOF">
        <details key="executionMetamodelElement"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="offeredTokens" upperBound="-1" eType="//States/activitydiagram/TracedControlToken">
        <eAnnotations source="aspect"/>
      </eStructuralFeatures>
      <eGenericSuperTypes eClassifier="//States/SpecificReferenceValue">
        <eTypeArguments eClassifier="//States/activitydiagram/TracedControlToken"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActivityNode_heldTokens_Dimension">
      <eGenericSuperTypes eClassifier="//States/SpecificDimension">
        <eTypeArguments eClassifier="//States/ActivityNode_heldTokens_Value"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActivityNode_heldTokens_Value">
      <eAnnotations source="http://www.modelexecution.org/trace/XMOF">
        <details key="executionMetamodelElement"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="heldTokens" upperBound="-1" eType="//States/activitydiagram/TracedControlToken">
        <eAnnotations source="aspect"/>
      </eStructuralFeatures>
      <eGenericSuperTypes eClassifier="//States/SpecificReferenceValue">
        <eTypeArguments eClassifier="//States/activitydiagram/TracedControlToken"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanVariable_currentValue_Dimension">
      <eGenericSuperTypes eClassifier="//States/SpecificDimension">
        <eTypeArguments eClassifier="//States/BooleanVariable_currentValue_Value"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanVariable_currentValue_Value" eSuperTypes="//States/SpecificAttributeValue">
      <eAnnotations source="http://www.modelexecution.org/trace/XMOF">
        <details key="executionMetamodelElement"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentValue" unique="false">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerVariable_currentValue_Dimension">
      <eGenericSuperTypes eClassifier="//States/SpecificDimension">
        <eTypeArguments eClassifier="//States/IntegerVariable_currentValue_Value"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerVariable_currentValue_Value" eSuperTypes="//States/SpecificAttributeValue">
      <eAnnotations source="http://www.modelexecution.org/trace/XMOF">
        <details key="executionMetamodelElement"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentValue" unique="false">
        <eAnnotations source="aspect"/>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SpecificAttributeValue" abstract="true" interface="true" eSuperTypes="//States/SpecificValue"/>
    <eClassifiers xsi:type="ecore:EClass" name="SpecificDimension" abstract="true">
      <eTypeParameters name="ValueSubType">
        <eBounds eClassifier="//States/SpecificValue"/>
      </eTypeParameters>
      <eGenericSuperTypes>
        <eTypeArguments eTypeParameter="//States/SpecificDimension/ValueSubType"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//Dimension"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SpecificReferenceValue" abstract="true" interface="true" eSuperTypes="//States/SpecificValue">
      <eTypeParameters name="T"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SpecificState">
      <eGenericSuperTypes>
        <eTypeArguments eClassifier="//Steps/SpecificStep"/>
        <eTypeArguments eClassifier="//States/SpecificValue"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//State"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SpecificTracedObject" abstract="true">
      <eTypeParameters name="DimensionSubType">
        <eBounds eClassifier="//States/SpecificDimension">
          <eTypeArguments>
            <eUpperBound eClassifier="//States/SpecificValue"/>
          </eTypeArguments>
        </eBounds>
      </eTypeParameters>
      <eGenericSuperTypes>
        <eTypeArguments eTypeParameter="//States/SpecificTracedObject/DimensionSubType"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//TracedObject"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SpecificValue" abstract="true">
      <eGenericSuperTypes>
        <eTypeArguments eClassifier="//States/SpecificState"/>
        <eClassifier xsi:type="ecore:EClass" href="../../../plugin/fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//Value"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eSubpackages name="activitydiagram" nsURI="activitydiagramTrace_activitydiagram" nsPrefix="">
      <eClassifiers xsi:type="ecore:EClass" name="TracedAction" abstract="true" eSuperTypes="//States/activitydiagram/TracedActivityNode">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedActivity" eSuperTypes="//States/activitydiagram/TracedNamedElement">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.xactivitydiagram/model/XActivityDiagram.ecore#//Activity"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedActivityEdge" abstract="true" eSuperTypes="//States/activitydiagram/TracedNamedElement">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;result.add(getActivityEdge_offeredTokens_Dimension());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="activityEdge_offeredTokens_Dimension" eType="//States/ActivityEdge_offeredTokens_Dimension" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedActivityFinalNode" eSuperTypes="//States/activitydiagram/TracedFinalNode">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.xactivitydiagram/model/XActivityDiagram.ecore#//ActivityFinalNode"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedActivityNode" abstract="true" eSuperTypes="//States/activitydiagram/TracedNamedElement">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;result.add(getActivityNode_heldTokens_Dimension());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="activityNode_heldTokens_Dimension" eType="//States/ActivityNode_heldTokens_Dimension" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedBooleanBinaryExpression" eSuperTypes="//States/activitydiagram/TracedBooleanExpression">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.xactivitydiagram/model/XActivityDiagram.ecore#//BooleanBinaryExpression"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedBooleanExpression" abstract="true" eSuperTypes="//States/activitydiagram/TracedExpression">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedBooleanUnaryExpression" eSuperTypes="//States/activitydiagram/TracedBooleanExpression">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.xactivitydiagram/model/XActivityDiagram.ecore#//BooleanUnaryExpression"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedBooleanValue" eSuperTypes="//States/activitydiagram/TracedValue //States/activitydiagram/TracedBooleanExpression">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.xactivitydiagram/model/XActivityDiagram.ecore#//BooleanValue"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedBooleanVariable" eSuperTypes="//States/activitydiagram/TracedVariable //States/activitydiagram/TracedBooleanExpression">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;result.add(getBooleanVariable_currentValue_Dimension());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="booleanVariable_currentValue_Dimension" eType="//States/BooleanVariable_currentValue_Dimension" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.xactivitydiagram/model/XActivityDiagram.ecore#//BooleanVariable"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedControlFlow" eSuperTypes="//States/activitydiagram/TracedActivityEdge">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.xactivitydiagram/model/XActivityDiagram.ecore#//ControlFlow"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedControlNode" abstract="true" eSuperTypes="//States/activitydiagram/TracedActivityNode">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedControlToken">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eGenericSuperTypes eClassifier="//States/SpecificTracedObject">
          <eTypeArguments eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eTypeArguments>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedDecisionNode" eSuperTypes="//States/activitydiagram/TracedControlNode">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.xactivitydiagram/model/XActivityDiagram.ecore#//DecisionNode"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedExpression" abstract="true">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eGenericSuperTypes eClassifier="//States/SpecificTracedObject">
          <eTypeArguments eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eTypeArguments>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedFinalNode" abstract="true" eSuperTypes="//States/activitydiagram/TracedControlNode">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedFlowFinalNode" eSuperTypes="//States/activitydiagram/TracedFinalNode">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.xactivitydiagram/model/XActivityDiagram.ecore#//FlowFinalNode"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedForkNode" eSuperTypes="//States/activitydiagram/TracedControlNode">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.xactivitydiagram/model/XActivityDiagram.ecore#//ForkNode"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedInitialNode" eSuperTypes="//States/activitydiagram/TracedControlNode">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.xactivitydiagram/model/XActivityDiagram.ecore#//InitialNode"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedIntegerBinaryExpression" eSuperTypes="//States/activitydiagram/TracedExpression //States/activitydiagram/TracedIntegerExpression">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.xactivitydiagram/model/XActivityDiagram.ecore#//IntegerBinaryExpression"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedIntegerComparisonExpression" eSuperTypes="//States/activitydiagram/TracedBooleanExpression">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.xactivitydiagram/model/XActivityDiagram.ecore#//IntegerComparisonExpression"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedIntegerExpression" abstract="true" eSuperTypes="//States/activitydiagram/TracedExpression">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedIntegerValue" eSuperTypes="//States/activitydiagram/TracedValue //States/activitydiagram/TracedIntegerExpression">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.xactivitydiagram/model/XActivityDiagram.ecore#//IntegerValue"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedIntegerVariable" eSuperTypes="//States/activitydiagram/TracedVariable //States/activitydiagram/TracedIntegerExpression">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;result.add(getIntegerVariable_currentValue_Dimension());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="integerVariable_currentValue_Dimension" eType="//States/IntegerVariable_currentValue_Dimension" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.xactivitydiagram/model/XActivityDiagram.ecore#//IntegerVariable"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedJoinNode" eSuperTypes="//States/activitydiagram/TracedControlNode">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.xactivitydiagram/model/XActivityDiagram.ecore#//JoinNode"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedMergeNode" eSuperTypes="//States/activitydiagram/TracedControlNode">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.xactivitydiagram/model/XActivityDiagram.ecore#//MergeNode"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedNamedElement" abstract="true">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eGenericSuperTypes eClassifier="//States/SpecificTracedObject">
          <eTypeArguments eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eTypeArguments>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedOffer">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eGenericSuperTypes eClassifier="//States/SpecificTracedObject">
          <eTypeArguments eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eTypeArguments>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedOpaqueAction" eSuperTypes="//States/activitydiagram/TracedAction">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject">
          <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.xactivitydiagram/model/XActivityDiagram.ecore#//OpaqueAction"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedValue" abstract="true" eSuperTypes="//States/activitydiagram/TracedExpression">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TracedVariable" abstract="true" eSuperTypes="//States/activitydiagram/TracedExpression">
        <eOperations name="getDimensionsInternal" upperBound="-1">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="final EList&lt;SpecificDimension&lt;?>> result = new org.eclipse.emf.ecore.util.BasicInternalEList&lt;SpecificDimension&lt;?>>(Object.class);&#xA;result.addAll(super.getDimensionsInternal());&#xA;return result;&#xA;"/>
          </eAnnotations>
          <eGenericType eClassifier="//States/SpecificDimension">
            <eTypeArguments/>
          </eGenericType>
        </eOperations>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
