# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Tycho Build

on:
  push:
    branches: 
      - '*'

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build Example Deployer update site 🔧
      run: |
          cd dev
          mvn -B clean package
          cd ..
          mkdir public
          mkdir public/updates
          mkdir public/updates/nightly
          cp -r dev/releng/org.gemoc.activitydiagram.repository/target/repository/* public/updates/nightly 
          
    
	- name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: public # The folder the action should deploy.